<?php

namespace App\Http\Requests\POS;

use Illuminate\Foundation\Http\FormRequest;

class SyncBatchRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true; // Authorization enforced by route middleware (permission:create_sale)
    }

    public function rules(): array
    {
        return [
            'batch_reference'                    => ['required', 'string', 'max:64'],
            'imports'                            => ['required', 'array', 'min:1', 'max:500'],
            'imports.*.offline_sequence_number'  => ['required', 'string'],
            'imports.*.submitted_at'             => ['required', 'date'],
            'imports.*.items'                    => ['required', 'array', 'min:1'],
            'imports.*.items.*.product_id'       => ['required', 'uuid'],
            'imports.*.items.*.quantity'         => ['required', 'integer', 'min:1'],
            'imports.*.items.*.unit_price'       => ['required', 'numeric', 'gt:0'],
            'imports.*.client_subtotal'          => ['required', 'numeric', 'min:0'],
            'imports.*.client_tax_total'         => ['required', 'numeric', 'min:0'],
            'imports.*.client_total'             => ['required', 'numeric', 'gt:0'],

            // 25 expanded audit metadata validation rules
            'imports.*.tenant_id'                => ['sometimes', 'nullable', 'uuid'],
            'imports.*.branch_id'                => ['sometimes', 'nullable', 'uuid'],
            'imports.*.terminal_id'              => ['sometimes', 'nullable', 'uuid'],
            'imports.*.device_id'                => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.user_id'                  => ['sometimes', 'nullable', 'uuid'],
            'imports.*.cashier_shift_id'         => ['sometimes', 'nullable', 'uuid'],
            'imports.*.shift_authorization_id'   => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.shift_authorization_policy_version' => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.shift_authorization_issued_at' => ['sometimes', 'nullable', 'date'],
            'imports.*.authorized_offline_until' => ['sometimes', 'nullable', 'date'],
            'imports.*.shift_status_snapshot'    => ['sometimes', 'nullable', 'string', 'in:open,closed,suspended,unknown'],
            'imports.*.shift_opened_at'          => ['sometimes', 'nullable', 'date'],
            'imports.*.shift_cached_at'          => ['sometimes', 'nullable', 'date'],
            'imports.*.timecard_id'              => ['sometimes', 'nullable', 'uuid'],
            'imports.*.local_transaction_reference'=> ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.local_receipt_number'      => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.official_receipt_number'   => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.official_invoice_number'   => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.server_sale_number'        => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.receipt_reference'         => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.e_journal_id'              => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.gct_id'                    => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.z_read_number'             => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.bir_receipt'               => ['sometimes', 'nullable', 'array'],
            'imports.*.final_posting_identity'    => ['sometimes', 'nullable', 'array'],
            'imports.*.business_date'            => ['sometimes', 'nullable', 'date_format:Y-m-d'],
            'imports.*.terminal_timestamp'       => ['sometimes', 'nullable', 'date'],
            'imports.*.timezone'                 => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.sales_machine_profile_id' => ['sometimes', 'nullable', 'uuid'],
            'imports.*.config_snapshot_hash'     => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.layout_version_hash'      => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.catalog_version_hash'     => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.tax_configuration_version_hash' => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.discount_rules_version_hash' => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.promotion_preview'      => ['sometimes', 'nullable', 'array'],
            'imports.*.applied_promotions'     => ['sometimes', 'nullable', 'array'],
            'imports.*.promotion_discount_centavos' => ['sometimes', 'integer', 'min:0'],
            'imports.*.commercial_discount_centavos' => ['sometimes', 'integer', 'min:0'],
            'imports.*.promotion_discount_amount' => ['sometimes', 'numeric', 'min:0'],
            'imports.*.statutory_discount'     => ['sometimes', 'nullable', 'array'],
            'imports.*.manager_approval_id'    => ['sometimes', 'nullable', 'uuid'],
            'imports.*.manager_approval'       => ['sometimes', 'nullable', 'array'],
            'imports.*.approval_id'            => ['sometimes', 'nullable', 'uuid'],
            'imports.*.approval_snapshot'      => ['sometimes', 'nullable', 'array'],
            'imports.*.payment_methods_version_hash' => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.terminal_policy_version_hash' => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.printer_profile_version_hash' => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.config_snapshot'          => ['sometimes', 'nullable', 'array'],
            'imports.*.cart_snapshot'            => ['sometimes', 'array'],
            'imports.*.payment_method'           => ['sometimes', 'string', 'in:cash,store_credit'],
            'imports.*.payments'                 => ['sometimes', 'array', 'min:1'],
            'imports.*.payments.*.payment_method_id' => ['required', 'uuid', 'exists:payment_methods,id'],
            'imports.*.payments.*.amount'        => ['required', 'numeric', 'gt:0'],
            'imports.*.payments.*.amount_centavos' => ['sometimes', 'integer', 'min:1'],
            'imports.*.payments.*.reference_number' => ['sometimes', 'nullable', 'string', 'max:100'],
            'imports.*.payments.*.payment_method_type_snapshot' => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.payments.*.payment_method_name_snapshot' => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.payments.*.payment_method_version' => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.payments.*.payment_method_configured_at' => ['sometimes', 'nullable', 'date'],
            'imports.*.payments.*.payment_method_configuration_hash' => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.gross_amount_centavos'    => ['sometimes', 'integer', 'min:0'],
            'imports.*.discount_total_centavos'  => ['sometimes', 'integer', 'min:0'],
            'imports.*.taxable_amount_centavos'  => ['sometimes', 'integer', 'min:0'],
            'imports.*.tax_amount_centavos'      => ['sometimes', 'integer', 'min:0'],
            'imports.*.net_amount_centavos'      => ['sometimes', 'integer', 'min:0'],
            'imports.*.payload_hash'             => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.business_payload_fingerprint' => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.fingerprint_algorithm'    => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.fingerprint_schema_version' => ['sometimes', 'integer', 'min:1'],
            'imports.*.schema_version'           => ['sometimes', 'integer', 'min:1'],
            'imports.*.sync_contract_version'    => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.cash_status'              => ['sometimes', 'nullable', 'string', 'in:not_collected,collected,returned'],
            'imports.*.resolution_status'        => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.customer_financial_account_id' => ['sometimes', 'nullable', 'uuid'],
            'imports.*.customer_snapshot_version' => ['sometimes', 'nullable', 'integer', 'min:1'],
            'imports.*.customer_snapshot_hash'   => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.customer_lookup_captured_at' => ['sometimes', 'nullable', 'date'],
            'imports.*.loyalty_expected'         => ['sometimes', 'boolean'],
            'imports.*.store_credit_redemption'  => ['sometimes', 'nullable', 'array'],
            'imports.*.store_credit_account_id'  => ['sometimes', 'nullable', 'uuid'],
            'imports.*.store_credit_ledger_entry_id' => ['sometimes', 'nullable', 'uuid'],
            'imports.*.store_credit_amount'      => ['sometimes', 'nullable', 'numeric', 'min:0'],
            'imports.*.local_sequence'           => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.drawer_session_id'        => ['sometimes', 'nullable', 'uuid'],
            'imports.*.cashier_id'               => ['sometimes', 'nullable', 'uuid'],
            'imports.*.sync_status'              => ['sometimes', 'nullable', 'string'],
            'imports.*.sync_attempt_count'       => ['sometimes', 'integer', 'min:0'],
            'imports.*.last_sync_attempt_at'     => ['sometimes', 'nullable', 'date'],
            'imports.*.previous_hash'            => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.row_hash'                 => ['sometimes', 'nullable', 'string', 'size:64'],
            'imports.*.offline_transaction_uuid' => ['sometimes', 'nullable', 'uuid'],
            'imports.*.terminal_binding_epoch'   => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.terminal_compromised'     => ['sometimes', 'boolean'],
            'imports.*.terminal_state'           => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.predecessor_dependency'   => ['sometimes', 'nullable', 'string', 'in:none,informational,strict'],
            'imports.*.strict_ordering'          => ['sometimes', 'boolean'],
            'imports.*.policy_drift_materiality' => ['sometimes', 'nullable', 'string', 'in:non_material,material_review,prohibited'],
            'imports.*.policy_drift_area'        => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.policy_drift_reason'      => ['sometimes', 'nullable', 'string', 'max:128'],
            'imports.*.clock_drift_minutes'      => ['sometimes', 'nullable', 'integer'],
            'imports.*.business_date_status'     => ['sometimes', 'nullable', 'string', 'max:64'],
            'imports.*.queue_state_revision'     => ['sometimes', 'integer', 'min:1'],
            'imports.*.sync_attempt_id'          => ['sometimes', 'nullable', 'uuid'],
            'imports.*.lease_id'                 => ['sometimes', 'nullable', 'uuid'],
            'imports.*.attempt_generation'       => ['sometimes', 'integer', 'min:1'],
        ];
    }

    public function messages(): array
    {
        return [
            'imports.*.items.*.unit_price.gt' => 'Each item unit_price must be greater than zero.',
            'imports.*.payments.*.payment_method_id.exists' => 'One or more payment methods are invalid.',
            'imports.*.payments.*.amount.gt' => 'Each payment amount must be greater than zero.',
        ];
    }
}
