<?php

namespace App\Services\Settlement;

use App\Models\AccountingOutbox;
use App\Models\SettlementPeriod;
use App\Models\User;
use App\Services\Accounting\AccountingOutboxQueryService;
use App\Services\AuditLogger;
use Illuminate\Auth\Access\AuthorizationException;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Storage;
use RuntimeException;

class SettlementExportService
{
    public function __construct(
        protected SettlementSummaryQueryService $summaryQuery,
        protected SettlementVarianceQueryService $varianceQuery,
        protected AccountingOutboxQueryService $outboxQuery,
        protected AuditLogger $auditLogger
    ) {}

    /**
     * Export the Settlement Summary report to a PDF string.
     */
    public function exportSummaryToPdf(SettlementPeriod $period, User $actor): string
    {
        $this->assertCanExport($period, $actor, 'export_reports');

        $data = $this->getSummaryData($period, $actor);
        $sourceMode = $this->determineSourceMode($period);

        $pdf = Pdf::loadView('reports.settlement-summary', [
            'data' => $data,
            'sourceMode' => $sourceMode,
            'branchName' => $period->branch?->name,
            'actorName' => $actor->name,
        ]);

        $output = $pdf->output();

        $this->logExport($period, $actor, 'summary', 'pdf', $sourceMode, 1);

        return $output;
    }

    /**
     * Export the Settlement Summary report to a CSV string.
     */
    public function exportSummaryToCsv(SettlementPeriod $period, User $actor): string
    {
        $this->assertCanExport($period, $actor, 'export_reports');

        $data = $this->getSummaryData($period, $actor);
        $sourceMode = $this->determineSourceMode($period);

        $handle = fopen('php://temp', 'r+');
        
        // Headers
        fputcsv($handle, ['Settlement Summary Report']);
        fputcsv($handle, ['Generated At', now()->toISOString()]);
        fputcsv($handle, ['Generated By', $actor->id]);
        fputcsv($handle, ['Source Mode', $sourceMode]);
        fputcsv($handle, []);

        fputcsv($handle, ['Field', 'Value']);
        fputcsv($handle, ['Period ID', $data['period']['id']]);
        fputcsv($handle, ['Tenant ID', $data['period']['tenant_id']]);
        fputcsv($handle, ['Branch ID', $data['period']['branch_id'] ?? 'N/A']);
        fputcsv($handle, ['Start At', $data['period']['period_start_at']]);
        fputcsv($handle, ['End At', $data['period']['period_end_at']]);
        fputcsv($handle, ['Status', $data['period']['status']]);
        fputcsv($handle, []);

        fputcsv($handle, ['Financial Totals']);
        fputcsv($handle, ['Gross Sales', $data['sales']['gross_sales_total']]);
        fputcsv($handle, ['Void Total', $data['sales']['void_total']]);
        fputcsv($handle, ['Refund Total', $data['sales']['refund_total']]);
        fputcsv($handle, ['Net Sales', $data['sales']['net_sales_total']]);
        fputcsv($handle, []);

        fputcsv($handle, ['Payment Method Breakdown']);
        fputcsv($handle, ['Method Code', 'Method Name', 'Total']);
        foreach ($data['payments']['by_method'] as $method) {
            fputcsv($handle, [$method['code'], $method['name'], $method['total']]);
        }
        fputcsv($handle, []);

        fputcsv($handle, ['Accounting Sync Summary']);
        foreach ($data['accounting_sync'] as $status => $count) {
            fputcsv($handle, [ucfirst($status), $count]);
        }

        rewind($handle);
        $csv = stream_get_contents($handle);
        fclose($handle);

        $this->logExport($period, $actor, 'summary', 'csv', $sourceMode, 1);

        return $csv;
    }

    /**
     * Export the Settlement Variance Ledger to a CSV string.
     */
    public function exportVariancesToCsv(SettlementPeriod $period, User $actor): string
    {
        $this->assertCanExport($period, $actor, 'export_accounting_reports');

        $data = $this->getVarianceData($period, $actor);
        $sourceMode = $this->determineSourceMode($period);

        $handle = fopen('php://temp', 'r+');
        
        fputcsv($handle, ['Category', 'Source Type', 'Source ID', 'Severity', 'Message', 'Amount']);

        foreach ($data['items'] as $item) {
            fputcsv($handle, [
                $item['category'],
                $item['source_type'],
                $item['source_id'],
                $item['severity'],
                $item['message'],
                $item['amount'],
            ]);
        }

        rewind($handle);
        $csv = stream_get_contents($handle);
        fclose($handle);

        $this->logExport($period, $actor, 'variance', 'csv', $sourceMode, count($data['items']));

        return $csv;
    }

    /**
     * Export the Accounting Sync Status Log to a CSV string.
     * Always uses live query but respects period boundaries and tenant/branch isolation.
     */
    public function exportSyncStatusToCsv(SettlementPeriod $period, User $actor): string
    {
        $this->assertCanExport($period, $actor, 'export_accounting_reports');

        $records = $this->outboxQuery->query([
            'branch_id' => $period->branch_id,
            'date_from' => $period->period_start_at->toDateString(),
            'date_to' => $period->period_end_at->toDateString(),
        ], $actor)
        ->whereBetween('created_at', [$period->period_start_at, $period->period_end_at])
        ->get();

        $handle = fopen('php://temp', 'r+');
        
        fputcsv($handle, [
            'Outbox ID', 
            'Event Type', 
            'Source Type', 
            'Source ID', 
            'Status', 
            'Attempts', 
            'Error Category',
            'Error Message', 
            'Created At', 
            'Synced At'
        ]);

        foreach ($records as $record) {
            $serialized = $this->outboxQuery->serializeSummary($record);
            fputcsv($handle, [
                $serialized['id'],
                $serialized['event_type'],
                $serialized['source_type'],
                $serialized['source_id'],
                $serialized['sync_status'],
                $serialized['attempt_count'],
                $serialized['sync_error_category'],
                $serialized['sync_error'],
                $serialized['created_at'],
                $serialized['synced_at'],
            ]);
        }

        rewind($handle);
        $csv = stream_get_contents($handle);
        fclose($handle);

        $this->logExport($period, $actor, 'accounting_sync_status', 'csv', 'live_query', $records->count());

        return $csv;
    }

    protected function getSummaryData(SettlementPeriod $period, User $actor): array
    {
        if ($period->status === SettlementPeriod::STATUS_LOCKED) {
            $snapshot = $period->latestSnapshot;
            if ($snapshot) {
                return $snapshot->summary_payload;
            }
        }

        return $this->summaryQuery->summarize($period, $actor);
    }

    protected function getVarianceData(SettlementPeriod $period, User $actor): array
    {
        if ($period->status === SettlementPeriod::STATUS_LOCKED) {
            $snapshot = $period->latestSnapshot;
            if ($snapshot) {
                return $snapshot->variance_payload;
            }
        }

        return $this->varianceQuery->summarize($period, $actor);
    }

    protected function determineSourceMode(SettlementPeriod $period): string
    {
        return ($period->status === SettlementPeriod::STATUS_LOCKED && $period->latestSnapshot)
            ? 'snapshot'
            : 'live_query';
    }

    protected function assertCanExport(SettlementPeriod $period, User $actor, string $permission): void
    {
        if (!$actor->hasPermission($permission)) {
            throw new AuthorizationException("Unauthorized. Permission required: {$permission}");
        }

        if ($period->tenant_id !== $actor->tenant_id) {
            throw new AuthorizationException('Tenant scope access denied for this settlement export.');
        }

        // Branch isolation check
        if (!$actor->hasPermission('view_multi_branch_dashboard')) {
            if ($period->branch_id === null) {
                throw new AuthorizationException('Branch-scoped users cannot export tenant-wide settlement reports.');
            }

            $allowedBranchIds = $actor->branches()->pluck('branches.id')->map(fn ($id) => (string) $id)->all();
            if (!in_array($period->branch_id, $allowedBranchIds, true)) {
                throw new AuthorizationException('Branch scope access denied for this settlement export.');
            }
        }
    }

    protected function logExport(
        SettlementPeriod $period, 
        User $actor, 
        string $type, 
        string $format, 
        string $sourceMode, 
        int $recordCount = 0
    ): void {
        $this->auditLogger->log(
            action: 'settlement_export_generated',
            auditable: $period,
            metadata: [
                'settlement_period_id' => $period->id,
                'report_type' => $type,
                'format' => $format,
                'scope' => $period->branch_id ? 'branch' : 'tenant',
                'branch_id' => $period->branch_id,
                'record_count' => $recordCount,
                'source_mode' => $sourceMode,
                'generated_by' => $actor->id,
                'generated_at' => now()->toIso8601String(),
            ]
        );
    }
}
